const products = [
  {
    id: 0,
    name: 'Mini Sofa',
    price: 79.99,
    instock: 22,
    description: 'blabla pff',
    imgSrc: 'Images/item1.jpg',
  },
  {
    id: 1,
    name: 'Old Fashioned Chair',
    price: 49.99,
    instock: 12,
    description: 'blabla pff',
    imgSrc: 'Images/item2.jpg',
  },
  {
    id: 2,
    name: 'Oak Cupboard',
    price: 109.99,
    instock: 7,
    description: 'blabla pff',
    imgSrc: 'Images/item3.jpg',
  },
  {
    id: 3,
    name: 'Modern Coffee Table',
    price: 59.99,
    instock: 46,
    description: 'blabla pff',
    imgSrc: 'Images/item4.jpg',
  },
  {
    id: 4,
    name: 'Small Table',
    price: 29.99,
    instock: 82,
    description: 'blabla pff',
    imgSrc: 'Images/item5.jpg',
  },
  {
    id: 5,
    name: 'Custom Chair',
    price: 39.99,
    instock: 32,
    description: 'blabla pff',
    imgSrc: 'Images/item6.jpg',
  },
  {
    id: 6,
    name: 'Wooden End Table',
    price: 49.99,
    instock: 13,
    description: 'blabla pff',
    imgSrc: 'Images/item7.jpg',
  },
  {
    id: 7,
    name: 'Garden Corner Sofa',
    price: 29.99,
    instock: 6,
    description: 'blabla pff',
    imgSrc: 'Images/item8.jpg',
  },
];
